version: '2'
services:
  # home-assistant home automation
  home:
    build: ./docker-homeassistant-armhf
    image: cultclassik/hass
#    image: lroguet/rpi-home-assistant
    container_name: ha-hass
    restart: always
    environment:
      VIRTUAL_HOST: "ha.diehlabs.tech,home.diehlabs.lan"
      WEBSOCKETS: 1
#      VIRTUAL_PROTO: uwsgi
      LETSENCRYPT_HOST: "ha.diehlabs.tech"
      LETSENCRYPT_EMAIL: "cultclassik@gmail.com"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/data/config/homeassistant-arm:/config
    expose:
      - 8123/tcp
#    ports:
#      - 8123:8123
    network_mode: bridge
    depends_on:
      - mqtt

  # mqtt broker
  mqtt:
    container_name: ha-mqtt
    build: ./docker-mosquitto-armhf
    image: mqtt
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/data/config/mqtt/config:/mqtt/config
      - /mnt/data/config/mqtt/log:/mqtt/log
      - /mnt/data/config/mqtt/data/:/mqtt/data
    ports:
      - 1883:1883
      - 9001:9001
    network_mode: bridge
