version: '2'
services:
  # home-assistant home automation
  home:
<<<<<<< HEAD
    container_name: home-homeassistant
    build: ./docker-homeassistant-armhf
    image: cultclassik/hass
=======
    container_name: ha-hass
    image: lsioarmhf/home-assistant
>>>>>>> ce608b46e74d2411c59cd7d7feae9400d7ff33b1
    restart: always
    environment:
      VIRTUAL_HOST: ha.diehlabs.tech,home.diehlabs.lan
      LETSENCRYPT_HOST: ha.diehlabs.tech
      LETSENCRYPT_EMAIL: "cultclassik@gmail.com"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/data/config/homeassistant-arm:/config
    expose:
      - 8123/tcp
    network_mode: bridge
    depends_on:
      - mqtt

  # mqtt broker
  mqtt:
    container_name: ha-mqtt
    build: ./docker-mosquitto-armhf
    image: mqtt
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/data/config/mqtt/config:/mqtt/config
      - /mnt/data/config/mqtt/log:/mqtt/log
      - /mnt/data/config/mqtt/data/:/mqtt/data
    ports:
      - 1883:1883
      - 9001:9001
    network_mode: bridge
