version: '2'
networks:
  proxy-tier:
    external:
      name: nginx-proxy

services:
  # home-assistant home automation
  home:
    build: ./docker-homeassistant-armhf
    image: cultclassik/hass
    container_name: ha-hass
    restart: always
    environment:
      VIRTUAL_HOST: "ha.diehlabs.tech,home.diehlabs.lan"
      WEBSOCKETS: 1
      LETSENCRYPT_HOST: "ha.diehlabs.tech"
      LETSENCRYPT_EMAIL: "cultclassik@gmail.com"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/data/config/homeassistant-arm:/config
    expose:
      - 8123/tcp
    networks:
      - proxy-tier
    depends_on:
      - mqtt

  # mqtt broker
  mqtt:
    container_name: ha-mqtt
    build: ./docker-mosquitto-armhf
    image: mqtt
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/data/config/mqtt/config:/mqtt/config
      - /mnt/data/config/mqtt/log:/mqtt/log
      - /mnt/data/config/mqtt/data/:/mqtt/data
    ports:
      - 1883:1883
      - 9001:9001
    network_mode: bridge

  firetv:
    build: ./docker-firetv-aarch64
    image: cultclassik/firetv-aarch64
    #build: ./docker-firetv-armhf
    #image: cultclassik/firetv-armhf
    container_name: ha-firetv
    restart: always
    environment:
      VIRTUAL_HOST: "firetv.diehlabs.lan"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/data/config/firetv:/config
    expose:
      - 5556/tcp
    networks:
      - proxy-tier
